# -*- coding: utf-8 -*-
"""AGENT M3GAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKDGxZmv2wkLDcYKEdoC8KVGmY6lh52y
"""

# create models.py
with open("models.py", "w") as f:
    f.write("""
def test_function():
    return "Hello from models.py"
""")

import models

print(models.test_function())

with open("models.py", "w") as f:
    f.write("""
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

def load_and_clean_data(path):
    df = pd.read_csv(path)
    df = df.drop_duplicates()
    df = df.dropna()
    return df

def feature_engineering(df):

    df = df.rename(columns={
        "TransactionAmount": "amount",
        "Location": "location"
    })

    if "TransactionDate" in df.columns:
        df["TransactionDate"] = pd.to_datetime(df["TransactionDate"], errors="coerce")
        df["hour"] = df["TransactionDate"].dt.hour
        df = df.dropna(subset=["hour"])

    drop_cols = [
        "TransactionID",
        "AccountID",
        "DeviceID",
        "IP Address",
        "MerchantID"
    ]

    df = df.drop(columns=[c for c in drop_cols if c in df.columns])

    df = pd.get_dummies(df, drop_first=True)

    return df

def train_model(df):
    X = df.select_dtypes(include=[np.number])

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    model = IsolationForest(contamination=0.05, random_state=42)
    model.fit(X_scaled)

    return model, scaler, X.columns

def score_transaction(transaction, model, scaler, feature_columns):
    df = pd.DataFrame([transaction])
    df = pd.get_dummies(df)
    df = df.reindex(columns=feature_columns, fill_value=0)

    X_scaled = scaler.transform(df)
    score = -model.decision_function(X_scaled)[0]

    return float(score)

def apply_rules(transaction):
    flags = []

    if transaction.get("amount", 0) > 3000:
        flags.append("High transaction amount")

    if transaction.get("location") not in ["Atlanta"]:
        flags.append("Unusual location")

    if transaction.get("hour", 12) < 5:
        flags.append("Late night activity")

    return flags

def make_decision(score, flags):
    if score > 0.8 or len(flags) >= 2:
        return "HIGH RISK"
    elif score > 0.5:
        return "MEDIUM RISK"
    else:
        return "LOW RISK"
""")

import importlib
import models
importlib.reload(models)

print(dir(models))

import importlib
import models
import agent

importlib.reload(models)
importlib.reload(agent)

with open("agent.py", "w") as f:
    f.write("""
from langgraph.graph import StateGraph
from models import score_transaction, apply_rules, make_decision

def build_agent(model, scaler, feature_columns):

    graph = StateGraph(dict)

    def anomaly_node(state):
        transaction = state.get("transaction", {})

        score = score_transaction(
            transaction,
            model,
            scaler,
            feature_columns
        )

        return {**state, "score": score}

    def rules_node(state):
        transaction = state.get("transaction", {})

        flags = apply_rules(transaction)

        return {**state, "flags": flags}

    def explain_node(state):
        explanation = f"Score: {state['score']:.2f}, Flags: {', '.join(state['flags'])}"
        return {**state, "explanation": explanation}

    def decision_node(state):
        decision = make_decision(state["score"], state["flags"])
        return {**state, "decision": decision}

    graph.add_node("anomaly", anomaly_node)
    graph.add_node("rules", rules_node)
    graph.add_node("explain", explain_node)
    graph.add_node("decision", decision_node)

    graph.set_entry_point("anomaly")
    graph.add_edge("anomaly", "rules")
    graph.add_edge("rules", "explain")
    graph.add_edge("explain", "decision")

    return graph.compile()
""")

import importlib
import agent

importlib.reload(agent)

import inspect
print(inspect.getsource(agent.build_agent))

agent_system = agent.build_agent(model, scaler, features)

result = agent_system.invoke({
    "transaction": test_tx
})

print(result)

from models import load_and_clean_data, feature_engineering, train_model
from agent import build_agent

# Load your dataset
df = load_and_clean_data("bank_transactions_data_2_augmented_clean_2 (2).csv")

def feature_engineering(df):

    # Rename columns to match your system
    df = df.rename(columns={
        "TransactionAmount": "amount",
        "Location": "location"
    })

    # Fix date parsing
    if "TransactionDate" in df.columns:
        df["TransactionDate"] = pd.to_datetime(
            df["TransactionDate"],
            errors="coerce"
        )

        df["hour"] = df["TransactionDate"].dt.hour

        df = df.dropna(subset=["hour"])

    # Drop non-useful ID columns (VERY IMPORTANT)
    drop_cols = [
        "TransactionID",
        "AccountID",
        "DeviceID",
        "IP Address",
        "MerchantID"
    ]

    df = df.drop(columns=[c for c in drop_cols if c in df.columns])

    # Encode categorical variables
    df = pd.get_dummies(df, drop_first=True)

    return df

# Train model
model, scaler, features = train_model(df)

# Build agent
agent_system = build_agent(model, scaler, features)

test_tx = {
    "amount": 4500,
    "location": "Atlanta",  # must match dataset values!
    "hour": 2
}

result = agent_system.invoke({"transaction": test_tx})

print(result)

with open("data.py", "w") as f:
    f.write("""
# paste your data.py code here
""")

import os
os.listdir()

import random
import time

for _ in range(5):

    tx = {
        "amount": random.randint(10, 5000),
        "location": random.choice(["Atlanta", "Houston", "Mesa"]),
        "hour": random.randint(0, 23)
    }

    print("Incoming Transaction:", tx)

    result = agent_system.invoke({"transaction": tx})

    print("Risk:", result["decision"])
    print("Score:", round(result["score"], 3))
    print("Flags:", result["flags"])
    print("Explanation:", result["explanation"])
    print("-" * 50)

    time.sleep(2)